# Travis CI будет использовать язык java.
language: java
install: true
sudo: false

script: mvn clean package -DskipTests=true

# Версия JDK для сборки проекта
jdk: openjdk11

services:
  - postgresql

addons:
  postgresql: "10"

os:
  - linux

dist: xenial

# Создать базу данных
before_install:
  - psql -c 'create database job4j_forum;' -U postgres

# После выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# И отправлять на сервис https://codecov.io/
after_success: bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="c7a2152a-1457-430a-be0e-22d9d8a2060a"
    - PGPORT=5432
    - PGUSER=postgres

notifications:
  email:
    recipients:
  -nasvit25@gmail.com
on_success: never # default: change
on_failure: always # default: always
