language: java
install: true
script: mvn clean package -DskipTests=true
jdk: openjdk11
services:
- postgresql
addons:
  postgresql: '10'
os:
- linux
dist: xenial
before_install:
- psql -c 'create database job4j_forum;' -U postgres
after_success: bash <(curl -s https://codecov.io/bash)
env:
  global:
  - CODECOV_TOKEN="c7a2152a-1457-430a-be0e-22d9d8a2060a"
  - PGPORT=5432
  - PGUSER=postgres
deploy:
  provider: heroku
  api_key:
    secure: GbuT48J81pMtD+lP3k84rtgsNxZK9Le1IeYc6mkNVddqzoV3hK0Yko9jVvuDMfzyKyNZWhthLgY3M7W6h2YbbgV7bejvgTCWeQCg59gSGIswxuw+jeNbyH+koBhIxID5B3VG3XGQ0/VCSQqmGm1du8hXZrko/zz9lx6mTVjvVIleGPbcHjP+UGOFpVrfAV8IrXLCCH1HrRIPQcLiHEcme5FfASgBmgvOCiUTJRfA3aSu1lm6cqEqLSx9ChUllzmPDLkCAGjCqWwIWnLEbCU+EqTJyEpx5O3prp7yPxO+f0Rq6BJm/Dw2It+5j1dsofcIth7cWHYMm6gjo21fiLWHH1w+rLOJDYtB+psCIYgSZeNd53XGwo8MsJeMFhGmqHzaHOYfMBz2sy4bnHP5UZ/OzJI4kclxA8RqTB0cSy08yw34/9Ka0LRLZMOr8/VLXDzz+4ZcUokY893FPVw1/m+t57dtxlqpCeGijBotkGYoNGE9sa2hufk6Jud1Isg++fy8ut12gZO0bPGbdPDTi9p28bCdylHwMet5DLX15nK2JpD7saSwPsi6azBc1K7AgOocpklzOhV4F1TEbwBehsF9C6NfFsu8kcevqemSkFNj9ejKtAo7DbnT2jeNrsSEgEiGaOsvNOhMYGzz0AaRiBeqtDKcMFqsGJ+ErMlXI6FBIiA=
  app: frozen-mountain-05627