language: java
install: true
script: mvn clean package -DskipTests=true
jdk: openjdk11
services:
- postgresql
addons:
  postgresql: '10'
os:
- linux
dist: xenial
before_install:
- psql -c 'create database job4j_forum;' -U postgres
after_success: bash <(curl -s https://codecov.io/bash)
env:
  global:
  - CODECOV_TOKEN="c7a2152a-1457-430a-be0e-22d9d8a2060a"
  - PGPORT=5432
  - PGUSER=postgres
deploy:
  provider: heroku
  api_key:
    secure: DR/TtWeq4Z9neqZXu6lpk7P+7gqILcAACH+0cMyUYcnpfGo+kL7tY8E2TlSxAjGqV9JXdaUj57nsa0HydNmRYSwO/3Z0oCmo7aYyM9NSQ1lfVVpr3VAAEvcJsMdtLrwhsqgu4Z4rmTn7MssOKgboYvowjrXzZ3YSE0ClJFyZGEarCt1c63q2svsMYCiJNl25CQd72LfIRz53ERFrsfM000yfWpGay4uEs/JzypNrh36mRU8YXH8HnxVATelmR7oWhXYFWWaTGOKrkCvkbygzJ0cNpqiWCZG6RZBo6Bwh/ywF3t7hL33pIk1VIym1pjTIsAGcPPIY6YgQZyDtzTZDhNQhpMEB3Sx1U40fuZXrm8qEbnsUN6uEDqvURo0hQQ4AGDKN+t11at0FfEXrsZh/XuC3CD8xBiKvlB+USZ7lABAh9iRBfyB45ihTWimnxhlfXKLqKpRAjp65FqH/DkNuhXtrKYQA5v0zg3tJHN3TpitvY2bdZLGLd0B0kAPZohERQ9zZx61eJiUu3+Fn6zW2gMNyVUB0Wr/y1v+5+rS+7Lh0ZT24H4tXkm75cHHXzFyHwy1ulMfgE7mc+UPeEkRZ3jH4UkVHHcVMqVu1BH/wYxQYLYPx3JQnXsp1ZfRNVKtjCfDdn3HGk1pN+nzwN3l42yfzvMavrgsikwWCWiu+YMY=
  app: frozen-mountain-05627